<?php

namespace AkademiaBundle\Repository;

/**
 * ApoderadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApoderadoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getbuscarApoderado($dni){

        $query ="select id from ACADEMIA.apoderado where dni='$dni' and estado=1";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $dni = $stmt->fetchAll();

    	return $dni;
	}

}
