<?php

namespace AkademiaBundle\Repository;

/**
 * AsistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
