<?php

namespace AkademiaBundle\Repository;

/**
 * AsistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMostrarAsistencia(){

            $query = "select * from academia.asistencia";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $asistencia = $stmt->fetchAll();

            return $asistencia;
    }
}
