<?php

namespace AkademiaBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMostrarCategoria(){

            $query = "select * from academia.categoria";
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            $categoria = $stmt->fetchAll();

            return $categoria;
    }
}
