<?php

namespace AkademiaBundle\Repository;

/**
 * ComplejoDisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplejoDisciplinaRepository extends \Doctrine\ORM\EntityRepository
{
}
