<?php

namespace AkademiaBundle\Repository;

/**
 * ComplejoDisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplejoDisciplinaRepository extends \Doctrine\ORM\EntityRepository
{

	public function getComplejoDisciplinas(){

       $query = "select  edi_codigo as id, edidis.ede_codigo as idComplejoDeportivo ,rtrim(dis.dis_descripcion) as nombreDisciplina, dis.dis_codigo as idDisciplina from CATASTRO.edificacionDisciplina as edidis, CATASTRO.disciplina as dis where edidis.dis_codigo = dis.dis_codigo;";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $complejosDeportivos = $stmt->fetchAll();

        return $complejosDeportivos;

	}

	public function getComplejosDisciplinasDiscaspacitados(){
		$query = "select  edi_codigo as id, edidis.ede_codigo as idComplejoDeportivo, rtrim(dis.dis_descripcion) as nombreDisciplina, dis.dis_codigo as idDisciplina ,ediComplejo.ede_discapacitado as discapacidad
			from CATASTRO.edificacionDisciplina as edidis inner join CATASTRO.disciplina as dis on edidis.dis_codigo = dis.dis_codigo inner join CATASTRO.edificacionesdeportivas as ediComplejo 
			on edidis.ede_codigo=ediComplejo.ede_codigo where ediComplejo.ede_discapacitado = 1";
		$stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $complejosDeportivos = $stmt->fetchAll();

        return $complejosDeportivos;
	}

}
