<?php

namespace AkademiaBundle\Repository;

/**
 * ComplejoDeportivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplejoDeportivoRepository extends \Doctrine\ORM\EntityRepository
{

	public function getComplejosDeportivos()
	{

       $query = "SELECT ede_codigo as id, ede_nombre as nombre ,ubicodigo , ede_direccion as direccion, ede_estado as estado, ede_discapacitado as discapacitado from CATASTRO.edificacionesdeportivas;";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $complejosDeportivos = $stmt->fetchAll();

        return $complejosDeportivos;        		
	}

	public function getComplejosDeportivosDiscapacitados()
	{
		$query = "SELECT ede_codigo as id, ede_nombre as nombre ,ubicodigo, ede_direccion as direccion, ede_estado as estado,ede_discapacitado as discapacidad from CATASTRO.edificacionesdeportivas where ede_discapacitado='1'";
		$stmt = $this->getEntityManager()->getConnection()->prepare($query);
		$stmt->execute();
		$complejosDeportivos = $stmt->fetchAll();

		return $complejosDeportivos;
	}

	public function getEditarDiscapacitado($idComplejo, $usuario){
	
		$query = "UPDATE catastro.edificacionesdeportivas set ede_discapacitado = 1, ede_usumodi = $usuario, ede_fechamodi = getDate() where ede_codigo= $idComplejo";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
	
	}

	public function nombreComplejo($idComplejo){

		$query = "SELECT b.ede_nombre as nombreComplejo from academia.usuario a inner join catastro.edificacionesdeportivas b on a.id_complejo = b.ede_codigo where a.id_complejo = $idComplejo";
		$stmt = $this->getEntityManager()->getConnection()->prepare($query);
		$stmt->execute();
		$nombre = $stmt->fetchAll();

		return $nombre;

	}

}
