<?php

namespace AkademiaBundle\Repository;

/**
 * DisciplinaDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaDeportivaRepository extends \Doctrine\ORM\EntityRepository
{
	   public function getDisciplinasDiferentes($idComplejo){
                
                $query = "select dis.dis_codigo, dis.dis_descripcion 
						from catastro.disciplina dis left join 
						(select d.dis_codigo, d.dis_descripcion 
						from catastro.edificacionDisciplina edi 
						inner join catastro.disciplina d on edi.dis_codigo = d.dis_codigo 
						inner join catastro.edificacionesdeportivas ede on edi.ede_codigo = ede.ede_codigo
						where ede.ede_codigo = $idComplejo) t2
						on dis.dis_codigo = t2.dis_codigo 
						where t2.dis_codigo IS NULL;";

                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $disciplinas = $stmt->fetchAll();

                return $disciplinas;
        }

        public function getMostrarCambios($idEdiDisciplina){

                $query = "select rtrim(b.dis_descripcion) as nombreDisciplina,b.dis_codigo as idDisciplina ,c.ede_discapacitado as discapacidad from CATASTRO.edificacionDisciplina as a inner join CATASTRO.disciplina as b on a.dis_codigo = b.dis_codigo inner join CATASTRO.edificacionesdeportivas as c on a.ede_codigo=c.ede_codigo where a.edi_codigo = $idEdiDisciplina";
                
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $disciplinas = $stmt->fetchAll();

                return $disciplinas;

        }
}
