<?php

namespace AkademiaBundle\Repository;

/**
 * DisciplinaDeportivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaDeportivaRepository extends \Doctrine\ORM\EntityRepository
{
}
