<?php

namespace AkademiaBundle\Repository;

/**
 * HorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioRepository extends \Doctrine\ORM\EntityRepository
{

        public function getHorarios(){

                $query = "select * from ACADEMIA.horario where convocatoria= 1  and vacantes <> 0 and estado = 1";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        }

        public function getHorariosPromotores(){
                
                $query = "select * from ACADEMIA.horario where estado = 1";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        }

        public function getHorariosVacantes($idHorario){
                $query = "select vacantes from ACADEMIA.horario where id = '$idHorario' ";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        }

        public function getHorariosDiscapacitados(){
        
                $query = "select * from ACADEMIA.horario where discapacitados = 1";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;

        }

        public function getHorariosComplejos($idcomplejo){
        
                $query ="select rtrim(dis.dis_descripcion) as nombreDisciplina,
                        dis.dis_codigo as idDisciplina,
                        hor.id as idHorario,
                        hor.turno as turno,
                        hor.estado as estadoHorario,
                        hor.discapacitados as discapacidad,
                        hor.edadMinima as edadMinima,
                        hor.edadMaxima as edadMaxima,
                        hor.horaInicio as horaInicio, 
                        hor.horaFin as horaFin, 
                        hor.vacantes as vacantes,
                        hor.convocatoria as convocatoria,
                        edi.edi_codigo as edi_codigo
                        from 
                        ACADEMIA.horario as hor inner join CATASTRO.edificacionDisciplina as edi on hor.edi_codigo = edi.edi_codigo
                        inner join CATASTRO.disciplina as dis on edi.dis_codigo = dis.dis_codigo
                        inner join CATASTRO.edificacionesdeportivas as ede on edi.ede_codigo = ede.ede_codigo
                        where ede.ede_codigo =$idcomplejo and dis.dis_estado = 1 and hor.estado = 1";

                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;

        }

        public function getHorariosIndividual($idHorario, $idDisciplina){
                
                $query = "select rtrim(dis.dis_descripcion) as nombreDisciplina,
                        dis.dis_codigo as idDisciplina,
                        hor.id as idHorario,
                        hor.turno as turno,
                        hor.discapacitados as discapacidad,
                        hor.edadMinima as edadMinima,
                        hor.edadMaxima as edadMaxima,
                        hor.horaInicio as horaInicio, 
                        hor.horaFin as horaFin, 
                        hor.vacantes as vacantes,
                        hor.convocatoria as convocatoria,
                        edi.edi_codigo as edi_codigo
                        from 
                        ACADEMIA.horario as hor inner join CATASTRO.edificacionDisciplina as edi on hor.edi_codigo = edi.edi_codigo
                        inner join CATASTRO.disciplina as dis on edi.dis_codigo = dis.dis_codigo
                        inner join CATASTRO.edificacionesdeportivas as ede on edi.ede_codigo = ede.ede_codigo
                        where dis.dis_codigo =$idDisciplina and hor.id = $idHorario";

                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        }

        public function getCapturarEdiCodigo($idComplejo, $idDisciplina){

                $query="select edi_codigo from catastro.edificacionDisciplina where ede_codigo = $idComplejo and dis_codigo = $idDisciplina";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        }

        public function getActualizarHorarios($idHorario, $vacantes, $convocatoria){

                $query = "update academia.horario set convocatoria = $convocatoria, vacantes = $vacantes from academia.horario where id = $idHorario";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();

        }

        public function getMostrarCambios($idHorario){

                $query = "select * from academia.horario where id='$idHorario'";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;

        }
        public function getActualizarVacantesHorarios($idHorario){

                $query = "update academia.horario set vacantes = (vacantes - 1) where id = $idHorario and vacantes > 0";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();

        }

        public function getAcumularInscritos($idHorario){

                $query = "update academia.horario set inscritos = (inscritos + 1) where id = $idHorario ";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
        
        }

        public function getHorarioBeneficiario($idHorario){

                $query = "select rtrim(dis.dis_descripcion) as nombreDisciplina,
                        dis.dis_codigo as idDisciplina,
                        hor.id as idHorario,
                        hor.turno as turno,
                        hor.inscritos as inscritos,
                        hor.discapacitados as discapacidad,
                        hor.edadMinima as edadMinima,
                        hor.edadMaxima as edadMaxima,
                        hor.horaInicio as horaInicio, 
                        hor.horaFin as horaFin, 
                        hor.vacantes as vacantes,
                        hor.convocatoria as convocatoria,
                        edi.edi_codigo as edi_codigo,
                        ede.ede_nombre as nombreComplejo
                        from 
                        ACADEMIA.horario as hor inner join CATASTRO.edificacionDisciplina as edi on hor.edi_codigo = edi.edi_codigo
                        inner join CATASTRO.disciplina as dis on edi.dis_codigo = dis.dis_codigo
                        inner join CATASTRO.edificacionesdeportivas as ede on edi.ede_codigo = ede.ede_codigo
                        where hor.id = $idHorario";

                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;
        
        }

        public function getBeneficiarios($idHorario){
                $query = "select (a.apellidoPaterno+' '+a.apellidoMaterno+' '+a.nombre) as nombre,
                        a.id as idParticipante,
                        a.dni as dni, (cast(datediff(dd,a.fechaNacimiento,GETDATE()) / 365.25 as int)) as edad,
                        a.sexo as sexo, 
                        a.estado as estadoParticipante,
                        b.id as idHorario, 
                        c.id as idInscribete,
                        c.estado as estadoInscribete   
                        from
                        academia.inscribete c inner join academia.horario b on c.horario_id = b.id 
                        inner join academia.participante a on c.participante_id = a.id where b.id = $idHorario and c.estado = 2";

                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $beneficiarios = $stmt->fetchAll();

                return $beneficiarios;
        }

        public function getDiferenciarHorarios($turno,$edadMinima,$edadMaxima,$horaInicio,$horaFin,$discapacitados){
               
                $query="select turno from academia.horario where turno ='$turno' and edadMinima=$edadMinima and edadMaxima=$edadMaxima and horaInicio='$horaInicio' and horaFin='$horaFin' and discapacitados=$discapacitados";
                $stmt = $this->getEntityManager()->getConnection()->prepare($query);
                $stmt->execute();
                $horarios = $stmt->fetchAll();

                return $horarios;

        }

}
