<?php

namespace AkademiaBundle\Repository;

/**
 * MovimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientosRepository extends \Doctrine\ORM\EntityRepository
{
}
