<?php

namespace AkademiaBundle\Repository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends \Doctrine\ORM\EntityRepository
{

	
}
